#### Import some basic Libraries and Packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

#### Importing the Training and Test set

In [2]:
train=pd.read_csv("data/train.csv")
test=pd.read_csv("data/test.csv")

In [3]:
print("Shape:",train.shape)
train.head()

Shape: (1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
print("Shape:",test.shape)
train.head()

Shape: (1459, 80)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

#### Combine both training and test file for data preprocessing and drop the SalePrice and ID columns

In [5]:
data=train.drop(["SalePrice"],axis=1).append(test,sort=False)
data.drop("Id",inplace=True,axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 79 columns):
MSSubClass       2919 non-null int64
MSZoning         2915 non-null object
LotFrontage      2433 non-null float64
LotArea          2919 non-null int64
Street           2919 non-null object
Alley            198 non-null object
LotShape         2919 non-null object
LandContour      2919 non-null object
Utilities        2917 non-null object
LotConfig        2919 non-null object
LandSlope        2919 non-null object
Neighborhood     2919 non-null object
Condition1       2919 non-null object
Condition2       2919 non-null object
BldgType         2919 non-null object
HouseStyle       2919 non-null object
OverallQual      2919 non-null int64
OverallCond      2919 non-null int64
YearBuilt        2919 non-null int64
YearRemodAdd     2919 non-null int64
RoofStyle        2919 non-null object
RoofMatl         2919 non-null object
Exterior1st      2918 non-null object
Exterior2nd      2918 non-null object
MasVnrType       2895 non-null object
MasVnrArea       2896 non-null float64
ExterQual        2919 non-null object
ExterCond        2919 non-null object
Foundation       2919 non-null object
BsmtQual         2838 non-null object
BsmtCond         2837 non-null object
BsmtExposure     2837 non-null object
BsmtFinType1     2840 non-null object
BsmtFinSF1       2918 non-null float64
BsmtFinType2     2839 non-null object
BsmtFinSF2       2918 non-null float64
BsmtUnfSF        2918 non-null float64
TotalBsmtSF      2918 non-null float64
Heating          2919 non-null object
HeatingQC        2919 non-null object
CentralAir       2919 non-null object
Electrical       2918 non-null object
1stFlrSF         2919 non-null int64
2ndFlrSF         2919 non-null int64
LowQualFinSF     2919 non-null int64
GrLivArea        2919 non-null int64
BsmtFullBath     2917 non-null float64
BsmtHalfBath     2917 non-null float64
FullBath         2919 non-null int64
HalfBath         2919 non-null int64
BedroomAbvGr     2919 non-null int64
KitchenAbvGr     2919 non-null int64
KitchenQual      2918 non-null object
TotRmsAbvGrd     2919 non-null int64
Functional       2917 non-null object
Fireplaces       2919 non-null int64
FireplaceQu      1499 non-null object
GarageType       2762 non-null object
GarageYrBlt      2760 non-null float64
GarageFinish     2760 non-null object
GarageCars       2918 non-null float64
GarageArea       2918 non-null float64
GarageQual       2760 non-null object
GarageCond       2760 non-null object
PavedDrive       2919 non-null object
WoodDeckSF       2919 non-null int64
OpenPorchSF      2919 non-null int64
EnclosedPorch    2919 non-null int64
3SsnPorch        2919 non-null int64
ScreenPorch      2919 non-null int64
PoolArea         2919 non-null int64
PoolQC           10 non-null object
Fence            571 non-null object
MiscFeature      105 non-null object
MiscVal          2919 non-null int64
MoSold           2919 non-null int64
YrSold           2919 non-null int64
SaleType         2918 non-null object
SaleCondition    2919 non-null object
dtypes: float64(11), int64(25), object(43)
memory usage: 1.8+ MB

#### Handelling Missing Values

In [6]:
#Removing all the columns which have null values more than 40 percent
s=pd.Series(train.isnull().sum()>584)
most_null=s.index[s.values==True]
data.drop(most_null,inplace=True,axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 74 columns):
MSSubClass       2919 non-null int64
MSZoning         2915 non-null object
LotFrontage      2433 non-null float64
LotArea          2919 non-null int64
Street           2919 non-null object
LotShape         2919 non-null object
LandContour      2919 non-null object
Utilities        2917 non-null object
LotConfig        2919 non-null object
LandSlope        2919 non-null object
Neighborhood     2919 non-null object
Condition1       2919 non-null object
Condition2       2919 non-null object
BldgType         2919 non-null object
HouseStyle       2919 non-null object
OverallQual      2919 non-null int64
OverallCond      2919 non-null int64
YearBuilt        2919 non-null int64
YearRemodAdd     2919 non-null int64
RoofStyle        2919 non-null object
RoofMatl         2919 non-null object
Exterior1st      2918 non-null object
Exterior2nd      2918 non-null object
MasVnrType       2895 non-null object
MasVnrArea       2896 non-null float64
ExterQual        2919 non-null object
ExterCond        2919 non-null object
Foundation       2919 non-null object
BsmtQual         2838 non-null object
BsmtCond         2837 non-null object
BsmtExposure     2837 non-null object
BsmtFinType1     2840 non-null object
BsmtFinSF1       2918 non-null float64
BsmtFinType2     2839 non-null object
BsmtFinSF2       2918 non-null float64
BsmtUnfSF        2918 non-null float64
TotalBsmtSF      2918 non-null float64
Heating          2919 non-null object
HeatingQC        2919 non-null object
CentralAir       2919 non-null object
Electrical       2918 non-null object
1stFlrSF         2919 non-null int64
2ndFlrSF         2919 non-null int64
LowQualFinSF     2919 non-null int64
GrLivArea        2919 non-null int64
BsmtFullBath     2917 non-null float64
BsmtHalfBath     2917 non-null float64
FullBath         2919 non-null int64
HalfBath         2919 non-null int64
BedroomAbvGr     2919 non-null int64
KitchenAbvGr     2919 non-null int64
KitchenQual      2918 non-null object
TotRmsAbvGrd     2919 non-null int64
Functional       2917 non-null object
Fireplaces       2919 non-null int64
GarageType       2762 non-null object
GarageYrBlt      2760 non-null float64
GarageFinish     2760 non-null object
GarageCars       2918 non-null float64
GarageArea       2918 non-null float64
GarageQual       2760 non-null object
GarageCond       2760 non-null object
PavedDrive       2919 non-null object
WoodDeckSF       2919 non-null int64
OpenPorchSF      2919 non-null int64
EnclosedPorch    2919 non-null int64
3SsnPorch        2919 non-null int64
ScreenPorch      2919 non-null int64
PoolArea         2919 non-null int64
MiscVal          2919 non-null int64
MoSold           2919 non-null int64
YrSold           2919 non-null int64
SaleType         2918 non-null object
SaleCondition    2919 non-null object
dtypes: float64(11), int64(25), object(38)
memory usage: 1.7+ MB

In [7]:
#Finding the columns which have null values
s1=pd.Series(data.isnull().sum()>0)
null_columns=s1.index[s1.values==True]
data[null_columns].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 29 columns):
MSZoning        2915 non-null object
LotFrontage     2433 non-null float64
Utilities       2917 non-null object
Exterior1st     2918 non-null object
Exterior2nd     2918 non-null object
MasVnrType      2895 non-null object
MasVnrArea      2896 non-null float64
BsmtQual        2838 non-null object
BsmtCond        2837 non-null object
BsmtExposure    2837 non-null object
BsmtFinType1    2840 non-null object
BsmtFinSF1      2918 non-null float64
BsmtFinType2    2839 non-null object
BsmtFinSF2      2918 non-null float64
BsmtUnfSF       2918 non-null float64
TotalBsmtSF     2918 non-null float64
Electrical      2918 non-null object
BsmtFullBath    2917 non-null float64
BsmtHalfBath    2917 non-null float64
KitchenQual     2918 non-null object
Functional      2917 non-null object
GarageType      2762 non-null object
GarageYrBlt     2760 non-null float64
GarageFinish    2760 non-null object
GarageCars      2918 non-null float64
GarageArea      2918 non-null float64
GarageQual      2760 non-null object
GarageCond      2760 non-null object
SaleType        2918 non-null object
dtypes: float64(11), object(18)
memory usage: 684.1+ KB

#### Seperating the Categorical and Numerical columns

In [8]:
cat_var=data.select_dtypes(include='object').columns
cat_info=data[cat_var].describe()
cat_info

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,Electrical,KitchenQual,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
count,2915,2919,2919,2919,2917,2919,2919,2919,2919,2919,...,2918,2918,2917,2762,2760,2760,2760,2919,2918,2919
unique,5,2,4,4,2,5,3,25,9,8,...,5,4,7,6,3,5,5,3,9,6
top,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,...,SBrkr,TA,Typ,Attchd,Unf,TA,TA,Y,WD,Normal
freq,2265,2907,1859,2622,2916,2133,2778,443,2511,2889,...,2671,1492,2717,1723,1230,2604,2654,2641,2525,2402

In [9]:
num_var=['MSSubClass', 'LotFrontage', 'LotArea','MasVnrArea','BsmtFinSF1',
             'BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
             'GrLivArea','GarageArea','WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
            'ScreenPorch', 'PoolArea', 'MiscVal']

num_info=data[num_var].describe()
num_info

,MSSubClass,LotFrontage,LotArea,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal
count,2919.000000,2433.000000,2919.000000,2896.000000,2918.000000,2918.000000,2918.000000,2918.000000,2919.000000,2919.000000,2919.000000,2919.000000,2918.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000
mean,57.137718,69.305795,10168.114080,102.201312,441.423235,49.582248,560.772104,1051.777587,1159.581706,336.483727,4.694416,1500.759849,472.874572,93.709832,47.486811,23.098321,2.602261,16.062350,2.251799,50.825968
std,42.517628,23.344905,7886.996359,179.334253,455.610826,169.205611,439.543659,440.766258,392.362079,428.701456,46.396825,506.051045,215.394815,126.526589,67.575493,64.244246,25.188169,56.184365,35.663946,567.402211
min,20.000000,21.000000,1300.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,59.000000,7478.000000,0.000000,0.000000,0.000000,220.000000,793.000000,876.000000,0.000000,0.000000,1126.000000,320.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,50.000000,68.000000,9453.000000,0.000000,368.500000,0.000000,467.000000,989.500000,1082.000000,0.000000,0.000000,1444.000000,480.000000,0.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,70.000000,80.000000,11570.000000,164.000000,733.000000,0.000000,805.500000,1302.000000,1387.500000,704.000000,0.000000,1743.500000,576.000000,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,190.000000,313.000000,215245.000000,1600.000000,5644.000000,1526.000000,2336.000000,6110.000000,5095.000000,2065.000000,1064.000000,5642.000000,1488.000000,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000

In [10]:
null_num_cat=['BsmtFullBath','BsmtHalfBath','GarageCars','GarageYrBlt']

#### Removing Outliers

In [11]:
# Removing outliers for numerical values
for var in num_var:
    mean=num_info.loc['mean',var]
    std=num_info.loc['std',var]
    uppr_limit=mean+3*std
    lower_limit=mean-3*std
    data.loc[data[var]>=uppr_limit,[var]]=uppr_limit
    data.loc[data[var]<=lower_limit,[var]]=lower_limit

In [12]:
# Filling the missing values
for var in cat_var:
    data[var].fillna(data[var].mode()[0],inplace=True)

for var in null_num_cat:
    data[var].fillna(data[var].mode()[0],inplace=True)

for var in num_var:
    data[var].fillna(data[var].mean(),inplace=True)

In [13]:
data.isnull().sum().sum()

0

#### Label Encoding

In [14]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

In [15]:
for var in cat_var:
    data[var] = labelencoder.fit_transform(data[var])

In [16]:
yr_columns=['YearBuilt','YearRemodAdd','GarageYrBlt','YrSold']
for var in yr_columns:
    data[var] = labelencoder.fit_transform(data[var])

In [17]:
data.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60.0,3,65.0,8450.0,1,3,3,0,4,0,...,61.0,0.000000,0.0,0.0,0.0,0.0,2,2,8,4
1,20.0,3,80.0,9600.0,1,3,3,0,2,0,...,0.0,0.000000,0.0,0.0,0.0,0.0,5,1,8,4
2,60.0,3,68.0,11250.0,1,0,3,0,4,0,...,42.0,0.000000,0.0,0.0,0.0,0.0,9,2,8,4
3,70.0,3,60.0,9550.0,1,0,3,0,0,0,...,35.0,215.831058,0.0,0.0,0.0,0.0,2,0,8,0
4,60.0,3,84.0,14260.0,1,0,3,0,2,0,...,84.0,0.000000,0.0,0.0,0.0,0.0,12,2,8,4

In [18]:
features=data.columns
features

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'GarageType', 'GarageYrBlt', 'GarageFinish',
       'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='object')

#### Feature Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
data[num_var]=sc.fit_transform(data[num_var])
data.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,0.070508,3,-0.201726,-0.308018,1,3,3,0,4,0,...,0.246300,-0.387685,-0.112533,-0.302895,-0.066884,-0.160183,2,2,8,4
1,-0.878057,3,0.555720,-0.060423,1,3,3,0,2,0,...,-0.758324,-0.387685,-0.112533,-0.302895,-0.066884,-0.160183,5,1,8,4
2,0.070508,3,-0.050237,0.294822,1,0,3,0,4,0,...,-0.066615,-0.387685,-0.112533,-0.302895,-0.066884,-0.160183,9,2,8,4
3,0.307649,3,-0.454208,-0.071188,1,0,3,0,0,0,...,-0.181900,3.534482,-0.112533,-0.302895,-0.066884,-0.160183,2,0,8,0
4,0.070508,3,0.757706,0.942874,1,0,3,0,2,0,...,0.625093,-0.387685,-0.112533,-0.302895,-0.066884,-0.160183,12,2,8,4

In [20]:
prssd_train_data=data[:1460]
prssd_train_data['SalePrice']=train['SalePrice']
prssd_test_data=data[1460:]

C:\Users\PP\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [21]:
X=prssd_train_data[features].values
y=prssd_train_data['SalePrice'].values

In [22]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

### Evaluation Function

In [23]:
from sklearn import metrics
def errors():
    print("MAE:",metrics.mean_absolute_error(y_test, y_pred))
    print("MSE:",metrics.mean_squared_error(y_test, y_pred))
    print("RMSE:",np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

### Linear Regression

In [24]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [25]:
y_pred=regressor.predict(X_test)

In [26]:
errors()

MAE: 22572.140540593402
MSE: 1696018964.6623528
RMSE: 41182.75081465968

### Support Vector Regressor

In [27]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf',C=20000,gamma=0.045)
regressor.fit(X_train,y_train)

SVR(C=20000, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.045,
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [28]:
y_pred=regressor.predict(X_test)

In [29]:
errors()

MAE: 50057.74818273185
MSE: 6402719555.638965
RMSE: 80016.99541746719

### Decision Tree

In [30]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [31]:
y_pred=regressor.predict(X_test)

In [32]:
errors()

MAE: 24975.238356164384
MSE: 1492197407.0082192
RMSE: 38628.97108399626

### Random forest

In [33]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=3000,random_state=0)
regressor.fit(X_train,y_train)

C:\Users\PP\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=3000, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [34]:
y_pred=regressor.predict(X_test)

In [35]:
errors()

MAE: 16421.92959269406
MSE: 839235072.9870131
RMSE: 28969.554242117934

### Gradient Boosting Regressor

In [36]:
from sklearn.ensemble import GradientBoostingRegressor
regressor=GradientBoostingRegressor(learning_rate=0.03, max_depth= 5, max_features= 'sqrt', min_samples_leaf= 15, min_samples_split= 15, n_estimators= 300)
regressor.fit(X_train,y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.03, loss='ls', max_depth=5,
             max_features='sqrt', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=15, min_samples_split=15,
             min_weight_fraction_leaf=0.0, n_estimators=300,
             presort='auto', random_state=None, subsample=1.0, verbose=0,
             warm_start=False)

In [37]:
y_pred=regressor.predict(X_test)

In [38]:
errors()

MAE: 15842.505313702832
MSE: 876417734.6091882
RMSE: 29604.35330503249

### XGBoost

In [39]:
from xgboost import XGBRegressor
regressor=XGBRegressor(learning_rate= 0.05,n_estimators= 3000)
regressor.fit(X_train,y_train)

[20:25:01] WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0,
       importance_type='gain', learning_rate=0.05, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=3000,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=None, subsample=1, verbosity=1)

In [40]:
y_pred=regressor.predict(X_test)

In [41]:
errors()

MAE: 15784.013217037671
MSE: 779484531.1499443
RMSE: 27919.250189608323

### Final Model

In [42]:
test_data=prssd_test_data[features].values

In [43]:
from sklearn.ensemble import GradientBoostingRegressor
regressor=GradientBoostingRegressor(learning_rate=0.03, max_depth= 5, max_features= 'sqrt', min_samples_leaf= 15, min_samples_split= 15, n_estimators= 300)
regressor.fit(X_train,y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.03, loss='ls', max_depth=5,
             max_features='sqrt', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=15, min_samples_split=15,
             min_weight_fraction_leaf=0.0, n_estimators=300,
             presort='auto', random_state=None, subsample=1.0, verbose=0,
             warm_start=False)

In [44]:
pred=regressor.predict(test_data)

In [45]:
pd.DataFrame({'Id':test.Id,'SalePrice':pred}).set_index('Id').to_csv('SubmissionGradBoost.csv')